services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sohri-api
    ports:
      - '9149:3000'
    volumes:
      - /home/ubuntu/.mago/data/sohri-api/logs:/app/logs
      - /home/ubuntu/.mago/data/sohri-api/results:/app/results
      - /app/node_modules  # 호스트의 node_modules는 컨테이너와 분리
    environment:
      - NODE_ENV=production
