services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sohri-api
    ports:
      - '9149:3000'
    volumes:
      - /home/ubuntu/.mago/data/sohri-api/logs:/app/logs
      - /home/ubuntu/.mago/data/sohri-api/results:/app/results
      - ./secrets/.env.enc.key:/app/secrets/.env.enc.key
    environment:
      NODE_ENV: ${NODE_ENV}
      WS_URL: ${WS_URL}
      SPEECH_API_URL: ${SPEECH_API_URL}
      SPEECH_API_TOKEN: ${SPEECH_API_TOKEN}
      TEMP_DIR: ${TEMP_DIR}
      WAV_DIR: ${WAV_DIR}
      RESULT_DIR: ${RESULT_DIR}
    command: npm run start:prod
#     networks:
#       - mago-services

# networks:
#   mago-services:
#     external: true
